export const ERROR_CODES = {
  // AUTH
  AUTH_EMAIL_REQUIRED: "AUTH_EMAIL_REQUIRED",
  AUTH_PASSWORD_REQUIRED: "AUTH_PASSWORD_REQUIRED",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_INVALID_EMAIL: "AUTH_INVALID_EMAIL",
  AUTH_WEAK_PASSWORD: "AUTH_WEAK_PASSWORD",
  AUTH_PASSWORD_MISMATCH: "AUTH_PASSWORD_MISMATCH",
  AUTH_TOKEN_MISSING: "AUTH_TOKEN_MISSING",
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_ACCOUNT_NOT_VERIFIED: "AUTH_ACCOUNT_NOT_VERIFIED",
  AUTH_ACCOUNT_LOCKED: "AUTH_ACCOUNT_LOCKED",
  AUTH_TOO_MANY_ATTEMPTS: "AUTH_TOO_MANY_ATTEMPTS",
  // USER
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  USERNAME_TAKEN: "USERNAME_TAKEN",

  // VALIDATION
  VALIDATION_FAILED: "VALIDATION_FAILED",
  INVALID_INPUT: "INVALID_INPUT",
  MISSING_REQUIRED_FIELDS: "MISSING_REQUIRED_FIELDS",

  // TOKEN / VERIFICATION
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  INVALID_VERIFICATION_TOKEN: "INVALID_VERIFICATION_TOKEN",

  // EMAIL / OTP
  EMAIL_SEND_FAILED: "EMAIL_SEND_FAILED",
  OTP_EXPIRED: "OTP_EXPIRED",
  OTP_INVALID: "OTP_INVALID",

  // SYSTEM
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  DATABASE_ERROR: "DATABASE_ERROR",

  // VEHICLE
  VEHICLE_PLATE_ALREADY_REGISTERED: "VEHICLE_PLATE_ALREADY_REGISTERED",
  VEHICLE_NOT_FOUND: "VEHICLE_NOT_FOUND",
  VEHICLE_INVALID_PLATE_FORMAT: "VEHICLE_INVALID_PLATE_FORMAT",
  VEHICLE_YEAR_OUT_OF_RANGE: "VEHICLE_YEAR_OUT_OF_RANGE",
  VEHICLE_INVALID_CAPACITY: "VEHICLE_INVALID_CAPACITY",

  // RIDE
  RIDE_NOT_FOUND: "RIDE_NOT_FOUND",
  RIDE_ALREADY_STARTED: "RIDE_ALREADY_STARTED",
  RIDE_ALREADY_COMPLETED: "RIDE_ALREADY_COMPLETED",
  RIDE_ALREADY_CANCELLED: "RIDE_ALREADY_CANCELLED",
  RIDE_SEATS_NOT_AVAILABLE: "RIDE_SEATS_NOT_AVAILABLE",
  RIDE_INVALID_ROUTE: "RIDE_INVALID_ROUTE",
  RIDE_INVALID_TIME: "RIDE_INVALID_TIME",
  RIDE_PAST_DEPARTURE_TIME: "RIDE_PAST_DEPARTURE_TIME",
  RIDE_DRIVER_VEHICLE_REQUIRED: "RIDE_DRIVER_VEHICLE_REQUIRED",
  RIDE_PICKUP_REQUIRED: "RIDE_PICKUP_REQUIRED",
  RIDE_DESTINATION_REQUIRED: "RIDE_DESTINATION_REQUIRED",
  RIDE_CANNOT_JOIN_OWN_RIDE: "RIDE_CANNOT_JOIN_OWN_RIDE",
  RIDE_ALREADY_JOINED: "RIDE_ALREADY_JOINED",
  RIDE_MAX_CAPACITY_REACHED: "RIDE_MAX_CAPACITY_REACHED",
  RIDE_INVALID_FARE: "RIDE_INVALID_FARE",
  RIDE_UNAUTHORIZED_ACTION: "RIDE_UNAUTHORIZED_ACTION",
  RIDE_NO_DATA_TO_UPDATE: "RIDE_NO_DATA_TO_UPDATE",

  // 🚖 RIDE REQUEST
  RIDE_REQUEST_NOT_FOUND: "RIDE_REQUEST_NOT_FOUND",
  RIDE_REQUEST_ALREADY_EXISTS: "RIDE_REQUEST_ALREADY_EXISTS",
  RIDE_REQUEST_ALREADY_ACCEPTED: "RIDE_REQUEST_ALREADY_ACCEPTED",
  RIDE_REQUEST_ALREADY_REJECTED: "RIDE_REQUEST_ALREADY_REJECTED",
  RIDE_REQUEST_ALREADY_CANCELLED: "RIDE_REQUEST_ALREADY_CANCELLED",
  RIDE_REQUEST_CANNOT_REQUEST_OWN_RIDE: "RIDE_REQUEST_CANNOT_REQUEST_OWN_RIDE",
  RIDE_REQUEST_RIDE_FULL: "RIDE_REQUEST_RIDE_FULL",
  RIDE_REQUEST_INVALID_STATUS: "RIDE_REQUEST_INVALID_STATUS",
  RIDE_REQUEST_UNAUTHORIZED_ACTION: "RIDE_REQUEST_UNAUTHORIZED_ACTION",
  RIDE_REQUEST_SEAT_LIMIT_EXCEEDED: "RIDE_REQUEST_SEAT_LIMIT_EXCEEDED",
  RIDE_REQUEST_RIDE_STARTED: "RIDE_REQUEST_RIDE_STARTED",
  RIDE_REQUEST_RIDE_COMPLETED: "RIDE_REQUEST_RIDE_COMPLETED",
  RIDE_REQUEST_RIDE_CANCELLED: "RIDE_REQUEST_RIDE_CANCELLED",
  RIDE_REQUEST_PASSENGER_NOT_FOUND: "RIDE_REQUEST_PASSENGER_NOT_FOUND",
  RIDE_REQUEST_DRIVER_NOT_FOUND: "RIDE_REQUEST_DRIVER_NOT_FOUND",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
