export const ERROR_CODES = {
  // AUTH
  AUTH_EMAIL_REQUIRED: "AUTH_EMAIL_REQUIRED",
  AUTH_PASSWORD_REQUIRED: "AUTH_PASSWORD_REQUIRED",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_INVALID_EMAIL: "AUTH_INVALID_EMAIL",
  AUTH_WEAK_PASSWORD: "AUTH_WEAK_PASSWORD",
  AUTH_PASSWORD_MISMATCH: "AUTH_PASSWORD_MISMATCH",
  AUTH_TOKEN_MISSING: "AUTH_TOKEN_MISSING",
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  AUTH_INVALID_PASSWORD: "AUTH_INVALID_PASSWORD",
  AUTH_ACCOUNT_NOT_VERIFIED: "AUTH_ACCOUNT_NOT_VERIFIED",
  AUTH_ACCOUNT_LOCKED: "AUTH_ACCOUNT_LOCKED",
  AUTH_TOO_MANY_ATTEMPTS: "AUTH_TOO_MANY_ATTEMPTS",
  // USER
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  USERNAME_TAKEN: "USERNAME_TAKEN",

  // VALIDATION
  VALIDATION_FAILED: "VALIDATION_FAILED",
  INVALID_INPUT: "INVALID_INPUT",
  MISSING_REQUIRED_FIELDS: "MISSING_REQUIRED_FIELDS",

  // TOKEN / VERIFICATION
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  INVALID_VERIFICATION_TOKEN: "INVALID_VERIFICATION_TOKEN",

  // EMAIL / OTP
  EMAIL_SEND_FAILED: "EMAIL_SEND_FAILED",
  OTP_EXPIRED: "OTP_EXPIRED",
  OTP_INVALID: "OTP_INVALID",

  // SYSTEM
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  DATABASE_ERROR: "DATABASE_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
